### ISSUE TITLE
2019 Roadmap

### ISSUE THREAD

**Issue by jamesmfriedman** [jamesmfriedman/rmwc#389]
Happy New Year Everyone! I wanted to take a minute to layout a proposed Roadmap for the year and give the community a chance to chime in / vote on new features and functionality. Anything is fair game so if you have any thoughts, call them out!

- [x] ## Converting Project to Typescript
Flow is fine for what it is. When this project was just a handful of components, it worked just fine. As RMWC has grown in complexity, some cracks in Flow have started to show through. The plan is to implement proper interfaces for all components, and clean up the external facing props api. As part of this effort, I'm also going to finish removing some old deprecated patterns that have been around from the start. As a bonus, material-components-web is converting to Typescript as well, so this should ensure a tight integration between the two.

If you rely on Flow, don't worry: RMWC will continue to have Flow support, it will just be generated types from the TS definitions. (Update, this has proved to be harder than expected and is not supported at this time)

- [x] ## Interactive / Realistic Docs Examples
Right now the docs are rendered working examples, but people have noticed they are written in a type of pseudo code with an implied global component. The goal here is to move to a framework that allows inline code editing, and shows complete examples.

- [x] ## Searchable / Versioned Docs
material-components-web changes pretty frequently, and as a result so does RMWC. If you want to stay on an old version of the codebase, you should be able to get back to the docs! The goal here is to provide a version dropdown so you can navigate to older versions at your leisure. 

- [x] ## End of React 15.x support
When RMWC started, React 16 was still in beta. Since then, they have continued to improve 16.x with some killer features, and made the upgrade path from 15 -> 16 seamless. 16.3 will be the new minimum version of React to take advantage or the React.Fragment syntax.

Have any ideas or requests? Drop them here.

Cheers,
James

**Comment by sadovnychyi** [comment]
Publishing es6 with `jsnext:main`/`module` pointer in package.json would help to reduce bundle size. Right now I have to install rmwc from git to get access to sources, but this will become broken when you move to TS.

**Comment by jamesmfriedman** [comment]
Good call! I’ve been wanting to tackle that anyways, I’ll make sure that happens with the typescript refactor.

**Comment by rjdestigter** [comment]
I would love to help the the TypeScript conversion!

**Comment by jamesmfriedman** [comment]
Awesome @rjdestigter. Ping me on Discord to communicate about it. I'll get the boilerplate / build setup first and then we can talk through some strategy. Would greatly appreciate the help.

**Comment by jamesmfriedman** [comment]
@sadovnychyi I now export a modules format the appropriate way for Webpack and Rollup to take advantage

**Comment by jamesmfriedman** [comment]
Sometimes you complete your roadmap 5 months into the year ;). If anyone has additional ideas, please open a new issue for a feature request
