### ISSUE TITLE
Official V1 Release Checklist

### ISSUE THREAD

**Issue by jamesmfriedman** [jamesmfriedman/rmwc#77]
Docs
- [x] New doc design
- [x] Mobile friendly docs
- [x] Docs home page
- [x] Docs project methodology page
- [x] Verify descriptions for all components
- [x] Document library-wide props
- [x] Move docs to docs folder instead of separate branch
- [x] Document RMWCProvider
- [x] Contributing guidelines
- [x] Add version number to docs
- [x] Fix 404 page

Other
- [x] Upgrade to MDC 28 (should release Jan 8)
- [x] RTL Support
- [x] No known bugs
- [x] Create "Simple" wrappers for complex components
- [x] Replace DefaultDialogTemplate with "SimpleDialog"
- [x] Remove non-spec IconButton
- [x] Add version number to build
- [x] Move build back to vanilla CRA with react-app-rewired
- [x] Fix umd build

**Comment by jamesmfriedman** [comment]
@j-o-d-o, I don't know if you have any bandwidth, but do you feel inclined to take any of this stuff on?

**Comment by j-o-d-o** [comment]
Have been quite busy the past week(s). But it looks much better as of next week!

Things I think I could take one: "MDC upgrade", "RTL support", "Verify descriptions for all components" and/or "Document library-wide props". 
But feel free to assign anything you would like to get done.

**Comment by jamesmfriedman** [comment]
RTL would be great. I have another issue open for it. Someone else expressed interest and then I never heard anything back. 

I think it literally might be just adding dir=“rtl” to the components which could be done through the spread props, but there are a few cases where the spread props don’t acrually go on the root node (like inputs and checkboxes).

**Comment by jamesmfriedman** [comment]
Hi @j-o-d-o, any word on rtl support?

**Comment by jamesmfriedman** [comment]
nvm, turns out you literally just have to add the prop `dir="rtl"`

**Comment by j-o-d-o** [comment]
Wow, you got some stuff done! Sorry for the delay. I looked through most of the changes and did some testing, looks good so far!
